policy:
  approval:
    - or:
        - FORCE_COMMIT
        - and:
            - review
            - sec_review

approval_rules:
  # rule to allow for forcible commits regardless of regular review process
  # this should be only used in the event of a site-outage and oncall is responding.
  - name: FORCE_COMMIT
    if:
      changed_files:
        paths:
          - ".*"
    requires:
      count: 1
      # only some users are allowed to give this sort of commit
      teams:
        - conduitxyz/org_design
        - conduitxyz/org_engineering
    options:
      allow_author: true
      allow_contributor: true
      methods:
        github_review: false
        comments:
          - FORCE_COMMIT

  - name: review
    if:
      changed_files:
        paths:
          - ".*"
    requires:
      count: 1
      teams:
        - conduitxyz/org_design
        - conduitxyz/org_engineering
    options:
      allow_author: false
      invalidate_on_push: true
      methods:
        github_review: true

  - name: sec_review
    if:
      changed_files:
        paths:
          - ".*"
    requires:
      count: 1
      teams:
        - conduitxyz/org_engineering_security
    options:
      allow_author: false
      invalidate_on_push: true
      methods:
        github_review: true
